#!/bin/sh
#
# Renders the router config from $HA_NODES and starts HAProxy.
#
# The node list is dynamic (one primary, any number of standbys), so the
# config is generated rather than shipped as a static file.
#
#   HA_NODES="nodeA=10.0.0.1:5432:8008,nodeB=10.0.0.2:5432:8008"
#             ^name  ^postgres host:port  ^agent port
#
# The first entry is the preferred primary. Every other node is declared a
# `backup` server, which gives HAProxy a deterministic tie-break: if two nodes
# ever claim to be primary at once (a network split), traffic stays with the
# original primary instead of flapping between them.
#
# Routing follows the agents, not this file: each node is health-checked with
# GET /primary, and only the node that answers 200 receives writes. A failover
# therefore needs no config change and no restart.

set -e

: "${HA_NODES:?HA_NODES must be set, e.g. nodeA=10.0.0.1:5432:8008,nodeB=10.0.0.2:5432:8008}"

WRITE_PORT="${HA_ROUTER_PORT:-5432}"
READ_PORT="${HA_ROUTER_READ_PORT:-5433}"
STATS_PORT="${HA_ROUTER_STATS_PORT:-8404}"
# How fast a dead primary is noticed: inter * fall.
CHECK_INTERVAL="${HA_ROUTER_CHECK_INTERVAL:-2s}"
CHECK_FALL="${HA_ROUTER_CHECK_FALL:-2}"
CFG="${HA_ROUTER_CONFIG:-/tmp/haproxy.cfg}"

# Emits one `server` line per node.
#   $1 = "backup" to mark every node after the first as a backup server
emit_servers() {
    mark_backup="$1"
    index=0
    OLD_IFS=$IFS
    IFS=,
    for entry in $HA_NODES; do
        IFS=$OLD_IFS
        name=${entry%%=*}
        addr=${entry#*=}
        host=$(echo "$addr" | cut -d: -f1)
        pg_port=$(echo "$addr" | cut -d: -f2)
        agent_port=$(echo "$addr" | cut -d: -f3)

        if [ -z "$name" ] || [ -z "$host" ] || [ -z "$pg_port" ] || [ -z "$agent_port" ]; then
            echo "ERROR: malformed HA_NODES entry '$entry'" >&2
            echo "       expected name=host:pgport:agentport" >&2
            exit 1
        fi

        flags=""
        if [ "$mark_backup" = "backup" ] && [ "$index" -gt 0 ]; then
            flags=" backup"
        fi
        # init-addr lets HAProxy start even while a node is unresolvable,
        # which matters when the other server is still booting.
        printf '    server %s %s:%s check port %s init-addr last,libc,none%s\n' \
            "$name" "$host" "$pg_port" "$agent_port" "$flags"
        index=$((index + 1))
        IFS=,
    done
    IFS=$OLD_IFS
}

cat > "$CFG" <<EOF
# Generated by render-haproxy.sh — edits are lost on restart.
global
    log stdout format raw local0 ${HA_ROUTER_LOG_LEVEL:-info}
    maxconn ${HA_ROUTER_MAXCONN:-4000}

defaults
    mode tcp
    log global
    option tcplog
    timeout connect 5s
    # Postgres connections are long-lived; do not cut idle sessions.
    timeout client ${HA_ROUTER_TIMEOUT:-8h}
    timeout server ${HA_ROUTER_TIMEOUT:-8h}
    timeout check 3s
    retries 2

# Writes: routed to whichever node reports itself primary.
listen pgsql-write
    bind *:${WRITE_PORT}
    option httpchk
    http-check send meth GET uri /primary
    http-check expect status 200
    # shutdown-sessions drops connections to a node the moment it stops being
    # the primary, so clients reconnect through the router and land on the new
    # one instead of sitting on a dead socket.
    default-server inter ${CHECK_INTERVAL} fall ${CHECK_FALL} rise 1 on-marked-down shutdown-sessions
$(emit_servers backup)

# Reads: spread over healthy, sufficiently caught-up standbys.
listen pgsql-read
    bind *:${READ_PORT}
    balance roundrobin
    option httpchk
    http-check send meth GET uri /replica
    http-check expect status 200
    default-server inter ${CHECK_INTERVAL} fall ${CHECK_FALL} rise 1 on-marked-down shutdown-sessions
$(emit_servers)

listen stats
    mode http
    bind *:${STATS_PORT}
    stats enable
    stats uri /
    stats refresh 5s
EOF

echo "--- rendered $CFG ---"
cat "$CFG"
echo "---------------------"

haproxy -c -f "$CFG"
exec haproxy -W -db -f "$CFG"
